/* Generated By:JavaCC: Do not edit this line. G1Constants.java */
package model.initialisation;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface G1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHAR = 5;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int INTEGER = 8;
  /** RegularExpression Id. */
  int PRIMARY = 9;
  /** RegularExpression Id. */
  int UNARY = 10;
  /** RegularExpression Id. */
  int BINARY = 11;
  /** RegularExpression Id. */
  int REGEX = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int ID = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<CHAR>",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGER>",
    "\"primaire\"",
    "\"unaire\"",
    "\"binaire\"",
    "<REGEX>",
    "<STRING>",
    "<ID>",
  };

}
