/* G2.java */
/* Generated By:JavaCC: Do not edit this line. G2.java */
package model.initialisation;
import java.util.ArrayList;
import model.*;
import java.io.InputStream;
public class G2 implements G2Constants {
        public static void main(String args[]) throws ParseException {
                G2 parser = new G2(System.in);
                Configuration.rules = new RulesConfiguration();
                parser.Rule();
        }
public static void readRules(InputStream stream) throws ParseException {
        G2 parser = new G2(stream);
        parser.RuleList();
}
        public static Expression readExpression(InputStream stream) throws ParseException {
                G2.ReInit(stream);
                Expression expression = Terme0();
                return new UnaryExpression("ROOT", expression);
        }

  static final public Expression Epsilon() throws ParseException {
{if ("" != null) return null;}
    throw new Error("Missing return statement in function");
  }

  static final public void RuleList() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ROOT_LEFT:
      case PARENTHESE_LEFT:
      case BRACKETS_LEFT:
      case ZERO:
      case UN:
      case DEUX:
      case TROIS:
      case QUATRE:
      case CINQ:
      case SIX:
      case SEPT:
      case HUIT:
      case NEUF:
      case EXPRESSION:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      Rule();
    }
    jj_consume_token(0);
  }

  static final public void Rule() throws ParseException {Expression exp1;
    exp1 = Terme0();
    RuleBis(exp1);
  }

  static final public void RuleBis(Expression exp1) throws ParseException {Expression exp2;
        Token input_type_rule;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LEFT_RULE_EQUIVALENT:{
      jj_consume_token(LEFT_RULE_EQUIVALENT);
      input_type_rule = jj_consume_token(RULE_INPUT_TYPE);
      jj_consume_token(RIGHT_RULE);
      exp2 = Terme0();
Configuration.rules.addRule(input_type_rule.image.substring(1), new Rule(exp1, exp2));
                Configuration.rules.addRule(input_type_rule.image.substring(1), new Rule(exp2, exp1));
                System.out.println(Configuration.rules.getRules());
      break;
      }
    case LEFT_RULE_NOT_EQUIVALENT:{
      jj_consume_token(LEFT_RULE_NOT_EQUIVALENT);
      input_type_rule = jj_consume_token(RULE_INPUT_TYPE);
      jj_consume_token(RIGHT_RULE);
      exp2 = Terme0();
Configuration.rules.addRule(input_type_rule.image.substring(1), new Rule(exp1, exp2));
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Axiome() throws ParseException {Expression exp;
    exp = Terme0();
    jj_consume_token(0);
System.out.println(exp.expressionToString());
  }

  static final public Expression Terme0() throws ParseException {Expression exp;
                Expression exp2;
    exp = Terme1();
    exp2 = Terme0Bis(exp);
{if ("" != null) return exp2 == null ? exp : exp2;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression Terme0Bis(Expression exp) throws ParseException {Token symbol;
        Expression exp1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS_OP:{
      symbol = jj_consume_token(PLUS_OP);
      exp1 = Terme0();
{if ("" != null) return new BinaryExpression("PLUS", exp, exp1);}
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      exp1 = Epsilon();
{if ("" != null) return exp1;}
    }
    throw new Error("Missing return statement in function");
  }

  static final public Expression Terme1() throws ParseException {Expression exp;
                Expression exp2;
    exp = Terme2();
    exp2 = Terme1Bis(exp);
{if ("" != null) return exp2 == null ? exp : exp2;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression Terme1Bis(Expression exp) throws ParseException {Token symbol;
        Expression exp1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMPO_OP:{
      symbol = jj_consume_token(COMPO_OP);
      exp1 = Terme1();
{if ("" != null) return new BinaryExpression("COMPO", exp, exp1);}
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      exp1 = Epsilon();
{if ("" != null) return exp1;}
    }
    throw new Error("Missing return statement in function");
  }

  static final public Expression Terme2() throws ParseException {Token symbol;
        Expression exp;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ROOT_LEFT:{
      symbol = jj_consume_token(ROOT_LEFT);
      exp = Terme2();
{if ("" != null) return new UnaryExpression("ROOT", exp);}
      break;
      }
    case PARENTHESE_LEFT:
    case BRACKETS_LEFT:
    case ZERO:
    case UN:
    case DEUX:
    case TROIS:
    case QUATRE:
    case CINQ:
    case SIX:
    case SEPT:
    case HUIT:
    case NEUF:
    case EXPRESSION:{
      exp = UnaireDroit();
{if ("" != null) return exp;}
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Expression UnaireDroit() throws ParseException {Expression primaire;
        Expression exp;
    primaire = Primaire();
    exp = UnaireDroitBis(primaire);
if(exp == null) {if ("" != null) return primaire;} {if ("" != null) return exp;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression UnaireDroitBis(Expression exp) throws ParseException {Token symbol;
        Expression exp2;
        Expression exp3;
    exp2 = Epsilon();
{if ("" != null) return exp2;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression Primaire() throws ParseException {Token symbolLeft;
        Token symbolRight;
        Expression expression;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PARENTHESE_LEFT:{
      symbolLeft = jj_consume_token(PARENTHESE_LEFT);
      expression = Terme0();
      symbolRight = jj_consume_token(PARENTHESE_RIGHT);
{if ("" != null) return new UnaryExpression("PARENTHESE",expression);}
      break;
      }
    case BRACKETS_LEFT:{
      symbolLeft = jj_consume_token(BRACKETS_LEFT);
      expression = Terme0();
      symbolRight = jj_consume_token(BRACKETS_RIGHT);
{if ("" != null) return expression;}
      break;
      }
    case ZERO:{
      symbolLeft = jj_consume_token(ZERO);
{if ("" != null) return new PrimaryExpression("ZERO",symbolLeft.image);}
      break;
      }
    case UN:{
      symbolLeft = jj_consume_token(UN);
{if ("" != null) return new PrimaryExpression("UN",symbolLeft.image);}
      break;
      }
    case DEUX:{
      symbolLeft = jj_consume_token(DEUX);
{if ("" != null) return new PrimaryExpression("DEUX",symbolLeft.image);}
      break;
      }
    case TROIS:{
      symbolLeft = jj_consume_token(TROIS);
{if ("" != null) return new PrimaryExpression("TROIS",symbolLeft.image);}
      break;
      }
    case QUATRE:{
      symbolLeft = jj_consume_token(QUATRE);
{if ("" != null) return new PrimaryExpression("QUATRE",symbolLeft.image);}
      break;
      }
    case CINQ:{
      symbolLeft = jj_consume_token(CINQ);
{if ("" != null) return new PrimaryExpression("CINQ",symbolLeft.image);}
      break;
      }
    case SIX:{
      symbolLeft = jj_consume_token(SIX);
{if ("" != null) return new PrimaryExpression("SIX",symbolLeft.image);}
      break;
      }
    case SEPT:{
      symbolLeft = jj_consume_token(SEPT);
{if ("" != null) return new PrimaryExpression("SEPT",symbolLeft.image);}
      break;
      }
    case HUIT:{
      symbolLeft = jj_consume_token(HUIT);
{if ("" != null) return new PrimaryExpression("HUIT",symbolLeft.image);}
      break;
      }
    case NEUF:{
      symbolLeft = jj_consume_token(NEUF);
{if ("" != null) return new PrimaryExpression("NEUF",symbolLeft.image);}
      break;
      }
    case EXPRESSION:{
      symbolLeft = jj_consume_token(EXPRESSION);
{if ("" != null) return new PrimaryExpression("EXPRESSION",symbolLeft.image);}
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public G2TokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[6];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x7ff580,0x3000000,0x20,0x40,0x7ff580,0x7ff500,};
   }

  /** Constructor with InputStream. */
  public G2(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public G2(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new G2TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public G2(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new G2TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public G2(G2TokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(G2TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[27];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 6; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 27; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
