/* Generated By:JavaCC: Do not edit this line. G2Constants.java */
package model.initialisation;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface G2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS_OP = 5;
  /** RegularExpression Id. */
  int COMPO_OP = 6;
  /** RegularExpression Id. */
  int ROOT_LEFT = 7;
  /** RegularExpression Id. */
  int PARENTHESE_LEFT = 8;
  /** RegularExpression Id. */
  int PARENTHESE_RIGHT = 9;
  /** RegularExpression Id. */
  int BRACKETS_LEFT = 10;
  /** RegularExpression Id. */
  int BRACKETS_RIGHT = 11;
  /** RegularExpression Id. */
  int ZERO = 12;
  /** RegularExpression Id. */
  int UN = 13;
  /** RegularExpression Id. */
  int DEUX = 14;
  /** RegularExpression Id. */
  int TROIS = 15;
  /** RegularExpression Id. */
  int QUATRE = 16;
  /** RegularExpression Id. */
  int CINQ = 17;
  /** RegularExpression Id. */
  int SIX = 18;
  /** RegularExpression Id. */
  int SEPT = 19;
  /** RegularExpression Id. */
  int HUIT = 20;
  /** RegularExpression Id. */
  int NEUF = 21;
  /** RegularExpression Id. */
  int EXPRESSION = 22;
  /** RegularExpression Id. */
  int RULE_INPUT_TYPE = 23;
  /** RegularExpression Id. */
  int LEFT_RULE_EQUIVALENT = 24;
  /** RegularExpression Id. */
  int LEFT_RULE_NOT_EQUIVALENT = 25;
  /** RegularExpression Id. */
  int RIGHT_RULE = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\".\"",
    "\"#\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"0\"",
    "\"1\"",
    "\"2\"",
    "\"3\"",
    "\"4\"",
    "\"5\"",
    "\"6\"",
    "\"7\"",
    "\"8\"",
    "\"9\"",
    "<EXPRESSION>",
    "<RULE_INPUT_TYPE>",
    "\"<=(\"",
    "\"=(\"",
    "\")=>\"",
  };

}
