/* Generated By:JavaCC: Do not edit this line. G2Constants.java */
package model.initialisation;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface G2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TURN_OP = 5;
  /** RegularExpression Id. */
  int BOARD_OP = 6;
  /** RegularExpression Id. */
  int CHKWIN_OP = 7;
  /** RegularExpression Id. */
  int DO_OP = 8;
  /** RegularExpression Id. */
  int ROW_OP = 9;
  /** RegularExpression Id. */
  int ROOT_LEFT = 10;
  /** RegularExpression Id. */
  int PARENTHESE_LEFT = 11;
  /** RegularExpression Id. */
  int PARENTHESE_RIGHT = 12;
  /** RegularExpression Id. */
  int VICTORY_LEFT = 13;
  /** RegularExpression Id. */
  int BRACKETS_LEFT = 14;
  /** RegularExpression Id. */
  int BRACKETS_RIGHT = 15;
  /** RegularExpression Id. */
  int SPACE = 16;
  /** RegularExpression Id. */
  int OMARK = 17;
  /** RegularExpression Id. */
  int XMARK = 18;
  /** RegularExpression Id. */
  int EXPRESSION = 19;
  /** RegularExpression Id. */
  int RULE_INPUT_TYPE = 20;
  /** RegularExpression Id. */
  int LEFT_RULE_EQUIVALENT = 21;
  /** RegularExpression Id. */
  int LEFT_RULE_NOT_EQUIVALENT = 22;
  /** RegularExpression Id. */
  int RIGHT_RULE = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"turn\"",
    "\",\"",
    "\"check\"",
    "\"applic\"",
    "\"|\"",
    "\"#\"",
    "\"(\"",
    "\")\"",
    "\"w\"",
    "\"{\"",
    "\"}\"",
    "\"_\"",
    "\"o\"",
    "\"x\"",
    "<EXPRESSION>",
    "<RULE_INPUT_TYPE>",
    "\"<=(\"",
    "\"=(\"",
    "\")=>\"",
  };

}
